# Generated by Django 6.0.2 on 2026-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "species_target",
                    models.CharField(
                        choices=[
                            ("dog", "Cachorro"),
                            ("cat", "Gato"),
                            ("both", "Ambos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doses_required", models.PositiveIntegerField(default=1)),
                (
                    "days_between_doses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
