# Generated by Django 6.0.2 on 2026-02-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccinations", "0001_initial"),
        ("vaccines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="vaccine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vaccines.vaccine"
            ),
        ),
    ]
